## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/residents"
  to = "https://welbi.org/api/residents"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "TOKEN"

  ## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/programs"
  to = "https://welbi.org/api/programs"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "TOKEN"